package visao;

import java.rmi.RemoteException;
import java.time.LocalDate;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import servico.IEmprestimo;
import servico.IAmigo;
import servico.IFerramenta;
import servico.AmigoService;
import servico.FerramentaService;
import servico.EmprestimoService;

public class FrmCadastroDevolucao extends javax.swing.JFrame {

    private transient IEmprestimo emprestimoService;
    private transient IAmigo amigoService;
    private transient IFerramenta ferramentaService;

    private String mensagem;

    public FrmCadastroDevolucao() {
        initComponents();
        try {
            this.emprestimoService = EmprestimoService.getInstanciaEmprestimo();
            this.amigoService = AmigoService.getInstanciaAmigo();
            this.ferramentaService = FerramentaService.getInstanciaFerramenta();
            this.carregaCBEmprestimo();
        } catch (Exception e) {
            mostrarMensagem("Erro ao conectar com o servidor: " + e.getMessage());
        }
    }

    public String getMensagem() {
        return mensagem;
    }

    public void setMensagem(String mensagem) {
        this.mensagem = mensagem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        javax.swing.JTextArea jTextArea1 = new javax.swing.JTextArea();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        comboBoxEmprestimo = new javax.swing.JComboBox<>();
        javax.swing.JButton buttonCancelar = new javax.swing.JButton();
        buttonCadatrar = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Devolução");

        jLabel1.setText("Empréstimo:");

        comboBoxEmprestimo.setMaximumRowCount(999);

        buttonCancelar.setText("Cancelar");
        buttonCancelar.addActionListener(this::buttonCancelarActionPerformed);

        buttonCadatrar.setText("Cadastrar");
        buttonCadatrar.addActionListener(this::buttonCadatrarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 226, Short.MAX_VALUE)
                        .addComponent(buttonCadatrar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCancelar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(comboBoxEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxEmprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 192, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonCancelar)
                    .addComponent(buttonCadatrar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCancelarActionPerformed
        if (evt == null) {
            return;
        }
        this.dispose();
    }//GEN-LAST:event_buttonCancelarActionPerformed

    private void buttonCadatrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCadatrarActionPerformed
                                             
        if (evt == null) return;
        try {
        int posicaoEmprestimo = comboBoxEmprestimo.getSelectedIndex();
            List<String[]> listaEmprestimo = emprestimoService.getListaEmprestimoAtivo();
            String[] emp = listaEmprestimo.get(posicaoEmprestimo);
            String data = LocalDate.now().toString();
            String[] dataInvertida = data.split("-");
            data = dataInvertida[2] + "-" + dataInvertida[1] + "-" + dataInvertida[0];

        if (emprestimoService.updateEmprestimoDB(
                    Integer.parseInt(emp[0]),
                    Integer.parseInt(emp[1]), 
                    Integer.parseInt(emp[2]), 
                    emp[3],                   
                    data                     
            )) {
                mostrarMensagem("Devolução cadastrada com sucesso.");
                comboBoxEmprestimo.removeAllItems();
                this.carregaCBEmprestimo();
            }
        } catch (Exception e) {
            mostrarMensagem("Erro ao cadastrar devolução: " + e.getMessage());
        }

    }//GEN-LAST:event_buttonCadatrarActionPerformed

    public void carregaCBEmprestimo() {
    try {
        List<String[]> listaEmprestimo = emprestimoService.getListaEmprestimoAtivo();
        List<String[]> listaAmigo = amigoService.listarTodos();
        List<String[]> listaFerramenta = ferramentaService.listarTodas();

        for (String[] emp : listaEmprestimo) {
            int idEmprestimo = Integer.parseInt(emp[0]);
            int idAmigo = Integer.parseInt(emp[1]);
            int idFerramenta = Integer.parseInt(emp[2]);

            // Busca o nome do amigo correspondente ao ID
            String nomeAmigo = listaAmigo.stream()
                .filter(a -> Integer.parseInt(a[0]) == idAmigo)
                .map(a -> a[1])
                .findFirst()
                .orElse("Amigo desconhecido");

            // Busca o nome da ferramenta correspondente ao ID
            String nomeFerramenta = listaFerramenta.stream()
                .filter(f -> Integer.parseInt(f[0]) == idFerramenta)
                .map(f -> f[1])
                .findFirst()
                .orElse("Ferramenta desconhecida");

            comboBoxEmprestimo.addItem(idEmprestimo + " - " + nomeAmigo + " - " + nomeFerramenta);
        }
    } catch (Exception e) {
        mostrarMensagem("Erro ao carregar empréstimos: " + e.getMessage());
    }
}

    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroDevolucao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FrmCadastroDevolucao().setVisible(true));

    }

    public void mostrarMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);
    }

    public JComboBox<String> getJCBEmprestimo() {
        return comboBoxEmprestimo;
    }

    protected javax.swing.JButton getJBCadastrar() {
        return this.buttonCadatrar;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCadatrar;
    private javax.swing.JComboBox<String> comboBoxEmprestimo;
    // End of variables declaration//GEN-END:variables
}
