package visao;

import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static servico.AmigoService.getInstanciaAmigo;
import servico.IAmigo;

public class FrmGerenciarAmigo extends javax.swing.JFrame {

    private transient IAmigo amigoService;

    private String mensagem;

    public FrmGerenciarAmigo() throws Exception {
        initComponents();          
            amigoService = getInstanciaAmigo();

        this.carregaListaAmigo();
        
    }

    public String getMensagem() {
        return mensagem;
    }

    public void setMensagem(String mensagem) {
        this.mensagem = mensagem;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        jTableAmigos = new javax.swing.JTable();
        javax.swing.JLabel labelId = new javax.swing.JLabel();
        javax.swing.JLabel labelNome = new javax.swing.JLabel();
        textNome = new javax.swing.JTextField();
        javax.swing.JLabel labelTelefone = new javax.swing.JLabel();
        textTelefone = new javax.swing.JTextField();
        buttonApagar = new javax.swing.JButton();
        buttonModificar = new javax.swing.JButton();
        javax.swing.JButton jBCancelar = new javax.swing.JButton();
        labelIid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Amigos");

        jTableAmigos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Telefone"
            }
        ));
        jTableAmigos.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableAmigosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableAmigos);

        labelId.setText("ID:");

        labelNome.setText("Nome:");

        labelTelefone.setText("Telefone:");

        buttonApagar.setText("Apagar");
        buttonApagar.addActionListener(this::buttonApagarActionPerformed);
        
        buttonModificar.setText("Modificar");
        buttonModificar.addActionListener(this::buttonModificarActionPerformed);
        
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(this::jBCancelarActionPerformed);

        labelIid.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelTelefone)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textTelefone))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNome)
                        .addGap(18, 18, 18)
                        .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelId)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelIid)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addComponent(buttonApagar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonModificar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBCancelar)
                .addGap(22, 22, 22))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelId)
                    .addComponent(labelIid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNome)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelTelefone)
                    .addComponent(textTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonApagar)
                    .addComponent(buttonModificar)
                    .addComponent(jBCancelar))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        //Libera todos os recurso da interface gráfica
        this.dispose();

    }//GEN-LAST:event_jBCancelarActionPerformed

    public void simularCliqueCancelar() {

        jBCancelarActionPerformed(null);
    }

    private void buttonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonModificarActionPerformed
        if (evt == null) {
            return;
        }
        try {
            
            int id = Integer.parseInt(labelIid.getText());
            String nome = textNome.getText().trim();
            String telefone = textTelefone.getText();

            if (amigoService.updateAmigoDB(id, nome,telefone)) {
                mostrarMensagem("Amigo atualizado com sucesso.");
                carregaListaAmigo();
            } else {
                mostrarMensagem("Falha ao atualizar o amigo.");
            }
        } catch (RemoteException ex) {
            ex.printStackTrace();
            mostrarMensagem("Erro ao conectar ao servidor RMI: " + ex.getMessage());
        }

        
    }//GEN-LAST:event_buttonModificarActionPerformed

    private void jTableAmigosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableAmigosMouseClicked
        if (evt == null) {
            return;
        }

        if (this.jTableAmigos.getSelectedRow() != -1) {
            labelIid.setText(jTableAmigos.getValueAt(this.jTableAmigos.getSelectedRow(), 0).toString());
            labelIid.setVisible(true);
            textNome.setText(jTableAmigos.getValueAt(this.jTableAmigos.getSelectedRow(), 1).toString());
            textTelefone.setText(jTableAmigos.getValueAt(this.jTableAmigos.getSelectedRow(), 2).toString());
        }
    }//GEN-LAST:event_jTableAmigosMouseClicked

    private void buttonApagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonApagarActionPerformed
        if (evt == null) {
            return;
        }
        try {
            if (jTableAmigos.getSelectedRow() == -1) {
                mostrarMensagem("Selecione um Amigo para apagar.");
                return;
            }

            int conf = JOptionPane.showConfirmDialog(null,
                    "Deseja realmente apagar este Amigo?",
                    "Confirmação",
                    JOptionPane.YES_NO_OPTION);

            if (conf != JOptionPane.YES_OPTION) return;

            int id = Integer.parseInt(labelIid.getText());

            if (amigoService.deleteAmigoDB(id)) {
                mostrarMensagem("Amigo apagado com sucesso.");
                textNome.setText("");
                labelIid.setText("");
                textTelefone.setText("");
                carregaListaAmigo();
            } else {
                mostrarMensagem("Falha ao apagar o amigo.");
            }

        } catch (RemoteException ex) {
            ex.printStackTrace();
            mostrarMensagem("Erro ao conectar ao servidor RMI: " + ex.getMessage());
        }

    }//GEN-LAST:event_buttonApagarActionPerformed
    public void carregaListaAmigo() {
        try{
        DefaultTableModel model = (DefaultTableModel) jTableAmigos.getModel();
        labelIid.setVisible(false);
        model.setNumRows(0);
        List<String[]> listaAmigo = amigoService.listarTodos();
        for (String[] amigo: listaAmigo) {
            model.addRow(new Object[]{amigo[0],amigo[1],amigo[2]}
            );
        }
    }catch(RemoteException e){
        
    }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmGerenciarAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new FrmGerenciarAmigo().setVisible(true);
            } catch (Exception ex) {
                Logger.getLogger(FrmGerenciarAmigo.class.getName()).log(Level.SEVERE, null, ex);
            }
        });

    }

    protected int confirmarApagarAmigo() {
        return JOptionPane.showConfirmDialog(null, "Esta ação também apagará todos os empréstimos associados a este amigo, deseja continuar?");
    }

    public void mostrarMensagem(String mensagem) {
        JOptionPane.showMessageDialog(null, mensagem);
    }

    protected javax.swing.JTextField getJTFNome() {
        return this.textNome;  // acesso direto porque está dentro da classe
    }

    protected javax.swing.JTextField getJTFTelefone() {
        return this.textTelefone;
    }

    protected javax.swing.JButton getJBModificar() {
        return this.buttonModificar;
    }

    protected javax.swing.JButton getJBApagar() {
        return this.buttonApagar;
    }

    protected javax.swing.JTable getJTableAmigos() {
        return this.jTableAmigos;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonApagar;
    private javax.swing.JButton buttonModificar;
    private javax.swing.JTable jTableAmigos;
    private javax.swing.JLabel labelIid;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textTelefone;
    // End of variables declaration//GEN-END:variables

}
