package visao;

import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import static servico.AmigoService.getInstanciaAmigo;
import static servico.EmprestimoService.getInstanciaEmprestimo;
import static servico.FerramentaService.getInstanciaFerramenta;
import servico.IAmigo;
import servico.IEmprestimo;
import servico.IFerramenta;

public class FrmRelatorio extends javax.swing.JFrame {

    public FrmRelatorio() throws Exception {
        initComponents();
        this.criaRelatorio();
        ferramentaService = getInstanciaFerramenta();
    }
    private static final Logger logger = Logger.getLogger(FrmRelatorio.class.getName());
    private transient IFerramenta ferramentaService;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        jTARelatorio = new javax.swing.JTextArea();
        javax.swing.JButton jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Relatório");

        jTARelatorio.setColumns(20);
        jTARelatorio.setRows(5);
        jScrollPane1.setViewportView(jTARelatorio);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 573, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (evt == null) {
            return;
        }
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
    public void criaRelatorio() throws Exception {
        int idAmigo = 0;
        int maior = 0;
        StringBuilder sb = new StringBuilder();
        double som = 0;
        IAmigo amigoService = getInstanciaAmigo();
        IEmprestimo emp = getInstanciaEmprestimo();
        List<String[]> listaAmigo = amigoService.listarTodos();
        List<String[]> listaFerramenta = ferramentaService.listarTodas();
        List<String[]> listaEmprestimo = emp.listaEmprestimo();

        for (String[] f : listaFerramenta) {
            sb.append("\n ID da Ferramenta: ").append(f[0])
                    .append("\n Nome da Ferramenta: ").append(f[1])
                    .append("\n Marca da Ferramenta: ").append(f[2])
                    .append("\n Custo da Ferramenta: ").append(f[3])
                    .append("\n");
            som += Double.parseDouble(f[3]);
        }

        sb.append("\n Custo total das ferramentas: R$").append(som).append("\n\n AMIGOS: \n");

        for (String[] a : listaAmigo) {
            int qtdEmprestimos = amigoService.quantidadeDeEmprestimos(Integer.parseInt(a[0]));
            boolean possuiAtivo = amigoService.possuiEmprestimoAtivo(Integer.parseInt(a[0]));

            sb.append("\n ID do Amigo: ").append(a[0])
                    .append("\n Nome do Amigo: ").append(a[1])
                    .append("\n Telefone do Amigo: ").append(a[2])
                    .append("\n Número de Empréstimos: ").append(qtdEmprestimos)
                    .append("\n Possui empréstimo ativo: ").append(possuiAtivo)
                    .append("\n");

            if (qtdEmprestimos > maior) {
                idAmigo = Integer.parseInt(a[1]);
                maior = qtdEmprestimos;
            }
        }

        sb.append("\n Amigo com maior quantidade de empréstimos: ")
                .append(amigoService.obterNomePorId(idAmigo))
                .append("\n Quantidade de empréstimos: ")
                .append(maior)
                .append("\n\n EMPRÉSTIMOS: \n");
        
        for (String[] e : listaEmprestimo) {

            sb.append("\n ID do Empréstimo: ").append(e[0])
                    .append("\n Nome do Amigo: ").append(amigoService.obterNomePorId(Integer.parseInt(e[1])))
                    .append("\n Nome da Ferramenta: ").append(ferramentaService.buscarNomePorId(Integer.parseInt(e[2])))
                    .append("\n Data de Início: ").append(e[3])
                    .append("\n Data de Devolução: ").append(e[4])
                    .append("\n");
        }
        jTARelatorio.setText(sb.toString());

    }

    public static void main(String[] args) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new FrmRelatorio().setVisible(true);
            } catch (Exception ex) {
                logger.log(Level.SEVERE, null, ex);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JTextArea jTARelatorio;
    // End of variables declaration//GEN-END:variables
}
